const CARD_ITEMS = [
  ['What is the capital of Abkhazia?', 'Sukhumi'],
  ['What is the capital of Afghanistan?', 'Kabul'],
  ['What is the capital of Åland Islands?', 'Mariehamn'],
  ['What is the capital of Albania?', 'Tirana'],
  ['What is the capital of Algeria?', 'Algiers'],
  [
    'What is the capital of Also known as Kotte.?',
    'Sri Jayawardenepura Kotte (official)',
  ],
  ['What is the capital of American Samoa?', 'Pago Pago'],
  ['What is the capital of Andorra?', 'Andorra la Vella'],
  ['What is the capital of Angola?', 'Luanda'],
  ['What is the capital of Anguilla?', 'The Valley'],
  ['What is the capital of Antigua and Barbuda?', "St. John's (de facto)"],
  ['What is the capital of Argentina?', 'Buenos Aires'],
  ['What is the capital of Armenia?', 'Yerevan'],
  ['What is the capital of Artsakh?', 'Stepanakert'],
  ['What is the capital of Aruba?', 'Oranjestad'],
  ['What is the capital of Ascension Island?', 'Georgetown'],
  ['What is the capital of Australia?', 'Canberra'],
  ['What is the capital of Austria?', 'Vienna'],
  ['What is the capital of Azerbaijan?', 'Baku'],
  ['What is the capital of Bahamas?', 'Nassau'],
  ['What is the capital of Bahrain?', 'Manama'],
  ['What is the capital of Bangladesh?', 'Dhaka'],
  ['What is the capital of Barbados?', 'Bridgetown'],
  ['What is the capital of Belarus?', 'Minsk'],
  ['What is the capital of Belgium?', 'Brussels'],
  ['What is the capital of Belize?', 'Belmopan'],
  [
    'What is the capital of Benin?',
    'Porto-Novo (official);  Cotonou (de facto)',
  ],
  ['What is the capital of Bermuda?', 'Hamilton'],
  ['What is the capital of Bhutan?', 'Thimphu'],
  [
    'What is the capital of Bolivia?',
    'La Paz (administrative);  Sucre (constitutional)',
  ],
  ['What is the capital of Bosnia and Herzegovina?', 'Sarajevo'],
  ['What is the capital of Botswana?', 'Gaborone'],
  [
    'What is the capital of Brazil?',
    'Brasília. Rio de Janeiro was the capital until 1960.',
  ],
  ['What is the capital of British Antarctic Territory?', 'Rothera'],
  [
    'What is the capital of British Indian Ocean Territory?',
    'Camp Thunder Cove',
  ],
  ['What is the capital of British Virgin Islands?', 'Road Town'],
  ['What is the capital of Brunei?', 'Bandar Seri Begawan'],
  ['What is the capital of Bulgaria?', 'Sofia'],
  ['What is the capital of Burkina Faso?', 'Ouagadougou'],
  [
    'What is the capital of Burundi?',
    'Gitega (official);  Bujumbura (de facto). Bujumbura was the capital from 1962 to 2018.',
  ],
  ['What is the capital of Cambodia?', 'Phnom Penh'],
  ['What is the capital of Cameroon?', 'Yaoundé'],
  ['What is the capital of Canada?', 'Ottawa'],
  ['What is the capital of Cape Verde?', 'Praia'],
  ['What is the capital of Cayman Islands?', 'George Town'],
  ['What is the capital of Central African Republic?', 'Bangui'],
  ['What is the capital of Chad?', "N'Djamena"],
  [
    'What is the capital of Chile?',
    'Santiago (official);  Valparaíso (legislative). The National Congress of Chile is located in Valparaíso.',
  ],
  ['What is the capital of China?', 'Beijing'],
  ['What is the capital of Christmas Island?', 'Flying Fish Cove'],
  ['What is the capital of Cocos (Keeling) Islands?', 'West Island'],
  ['What is the capital of Colombia?', 'Bogotá'],
  ['What is the capital of Comoros?', 'Moroni'],
  ['What is the capital of Congo?', 'Brazzaville'],
  ['What is the capital of Cook Islands?', 'Avarua'],
  ['What is the capital of Costa Rica?', 'San José'],
  ['What is the capital of Croatia?', 'Zagreb'],
  ['What is the capital of Cuba?', 'Havana'],
  ['What is the capital of Curaçao?', 'Willemstad'],
  ['What is the capital of Cyprus / Northern Cyprus?', 'Nicosia'],
  [
    'What is the capital of Czech Republic?',
    'Prague (official, legislative and executive); Brno (judiciary)',
  ],
  ['What is the capital of Democratic Republic of the Congo?', 'Kinshasa'],
  ['What is the capital of Denmark?', 'Copenhagen'],
  ['What is the capital of Djibouti?', 'Djibouti'],
  ['What is the capital of Dominica?', 'Roseau'],
  ['What is the capital of Dominican Republic?', 'Santo Domingo'],
  ['What is the capital of East Timor?', 'Dili'],
  ['What is the capital of Ecuador?', 'Quito'],
  ['What is the capital of Egypt?', 'Cairo'],
  ['What is the capital of El Salvador?', 'San Salvador'],
  ['What is the capital of Equatorial Guinea?', 'Malabo'],
  ['What is the capital of Eritrea?', 'Asmara'],
  ['What is the capital of Estonia?', 'Tallinn'],
  [
    'What is the capital of Eswatini?',
    'Lobamba (royal and legislative);  Mbabane (administrative)',
  ],
  ['What is the capital of Ethiopia?', 'Addis Ababa'],
  ['What is the capital of Falkland Islands?', 'Stanley'],
  ['What is the capital of Faroe Islands?', 'Tórshavn'],
  ['What is the capital of Fiji?', 'Suva'],
  ['What is the capital of Finland?', 'Helsinki'],
  ['What is the capital of France?', 'Paris'],
  ['What is the capital of French Polynesia?', 'Papeete'],
  ['What is the capital of Gabon?', 'Libreville'],
  ['What is the capital of Georgia?', 'Tbilisi'],
  ['What is the capital of Germany?', 'Berlin'],
  ['What is the capital of Ghana?', 'Accra'],
  ['What is the capital of Gibraltar?', 'Gibraltar'],
  ['What is the capital of Greece?', 'Athens'],
  ['What is the capital of Greenland?', 'Nuuk'],
  ['What is the capital of Grenada?', "St. George's"],
  ['What is the capital of Guam?', 'Hagåtña'],
  ['What is the capital of Guatemala?', 'Guatemala City'],
  ['What is the capital of Guernsey?', 'St. Peter Port'],
  ['What is the capital of Guinea?', 'Conakry'],
  ['What is the capital of Guinea-Bissau?', 'Bissau'],
  ['What is the capital of Guyana?', 'Georgetown'],
  ['What is the capital of Haiti?', 'Port-au-Prince'],
  [
    'What is the capital of Honduras?',
    'Tegucigalpa / Comayagüela. Comayagüela is declared in the Honduran Constitution as co-official capital with Tegucigalpa.[11] Now they have merged into a single Metropolitan Area.',
  ],
  ['What is the capital of Hungary?', 'Budapest'],
  ['What is the capital of Iceland?', 'Reykjavík'],
  ['What is the capital of India?', 'New Delhi'],
  ['What is the capital of Indonesia?', 'Jakarta'],
  ['What is the capital of Iran?', 'Tehran'],
  ['What is the capital of Iraq?', 'Baghdad'],
  ['What is the capital of Ireland?', 'Dublin'],
  ['What is the capital of Isle of Man?', 'Douglas'],
  [
    'What is the capital of Israel?',
    'Jerusalem;  Palestine;  Ramallah (de facto)',
  ],
  ['What is the capital of Italy?', 'Rome'],
  ['What is the capital of Ivory Coast?', 'Yamoussoukro'],
  ['What is the capital of Jamaica?', 'Kingston'],
  ['What is the capital of Japan?', 'Tokyo'],
  ['What is the capital of Jersey?', 'St. Helier'],
  ['What is the capital of Jordan?', 'Amman'],
  ['What is the capital of Kazakhstan?', 'Astana'],
  ['What is the capital of Kenya?', 'Nairobi'],
  ['What is the capital of Kiribati?', 'South Tarawa'],
  ['What is the capital of Kosovo?', 'Pristina'],
  ['What is the capital of Kuwait?', 'Kuwait City'],
  ['What is the capital of Kyrgyzstan?', 'Bishkek'],
  ['What is the capital of Laos?', 'Vientiane'],
  ['What is the capital of Latvia?', 'Riga'],
  ['What is the capital of Lebanon?', 'Beirut'],
  ['What is the capital of Lesotho?', 'Maseru'],
  ['What is the capital of Liberia?', 'Monrovia'],
  ['What is the capital of Libya?', 'Tripoli'],
  ['What is the capital of Liechtenstein?', 'Vaduz'],
  ['What is the capital of Lithuania?', 'Vilnius'],
  ['What is the capital of Luxembourg?', 'Luxembourg'],
  ['What is the capital of Madagascar?', 'Antananarivo'],
  ['What is the capital of Malawi?', 'Lilongwe'],
  [
    'What is the capital of Malaysia?',
    'Kuala Lumpur (official, legislative and royal); Putrajaya (administrative and judicial)',
  ],
  ['What is the capital of Maldives?', 'Malé'],
  ['What is the capital of Mali?', 'Bamako'],
  ['What is the capital of Malta?', 'Valletta'],
  ['What is the capital of Marshall Islands?', 'Majuro'],
  ['What is the capital of Mauritania?', 'Nouakchott'],
  ['What is the capital of Mauritius?', 'Port Louis'],
  ['What is the capital of Mexico?', 'Mexico City'],
  ['What is the capital of Micronesia?', 'Palikir'],
  ['What is the capital of Moldova?', 'Chișinău'],
  ['What is the capital of Monaco?', 'Monaco'],
  ['What is the capital of Mongolia?', 'Ulaanbaatar'],
  [
    'What is the capital of Montenegro?',
    'Podgorica (official); Cetinje (Old Royal Capital, present seat of the President)',
  ],
  [
    'What is the capital of Montserrat?',
    'Brades (de facto);  Plymouth (official) ',
  ],
  ['What is the capital of Morocco?', 'Rabat'],
  ['What is the capital of Mozambique?', 'Maputo'],
  ['What is the capital of Myanmar?', 'Naypyidaw'],
  ['What is the capital of Namibia?', 'Windhoek'],
  ['What is the capital of Nauru?', 'Yaren (de facto)'],
  ['What is the capital of Nepal?', 'Kathmandu'],
  [
    'What is the capital of Netherlands?',
    'Amsterdam (official); The Hague (de facto). The Dutch constitution refers to Amsterdam as the "capital"',
  ],
  ['What is the capital of New Caledonia?', 'Nouméa'],
  ['What is the capital of New Zealand?', 'Wellington'],
  ['What is the capital of Nicaragua?', 'Managua'],
  ['What is the capital of Niger?', 'Niamey'],
  ['What is the capital of Nigeria?', 'Abuja'],
  ['What is the capital of Niue?', 'Alofi'],
  ['What is the capital of Norfolk Island?', 'Kingston'],
  ['What is the capital of North Korea?', 'Pyongyang'],
  ['What is the capital of North Macedonia?', 'Skopje'],
  ['What is the capital of Northern Ireland?', 'Belfast'],
  ['What is the capital of Northern Mariana Islands?', 'Saipan'],
  ['What is the capital of Norway?', 'Oslo'],
  ['What is the capital of Oman?', 'Muscat'],
  ['What is the capital of Pakistan?', 'Islamabad'],
  ['What is the capital of Palau?', 'Ngerulmud'],
  ['What is the capital of Panama?', 'Panama City'],
  ['What is the capital of Papua New Guinea?', 'Port Moresby'],
  ['What is the capital of Paraguay?', 'Asunción'],
  ['What is the capital of Peru?', 'Lima'],
  ['What is the capital of Philippines?', 'Manila'],
  ['What is the capital of Pitcairn Islands?', 'Adamstown'],
  ['What is the capital of Poland?', 'Warsaw'],
  ['What is the capital of Portugal?', 'Lisbon'],
  ['What is the capital of Puerto Rico?', 'San Juan'],
  ['What is the capital of Qatar?', 'Doha'],
  ['What is the capital of Romania?', 'Bucharest'],
  ['What is the capital of Russia?', 'Moscow'],
  ['What is the capital of Rwanda?', 'Kigali'],
  ['What is the capital of Saint Barthélemy?', 'Gustavia'],
  ['What is the capital of Saint Helena?', 'Jamestown'],
  ['What is the capital of Saint Kitts and Nevis?', 'Basseterre'],
  ['What is the capital of Saint Lucia?', 'Castries'],
  ['What is the capital of Saint Martin?', 'Marigot'],
  ['What is the capital of Saint Pierre and Miquelon?', 'St. Pierre'],
  ['What is the capital of Saint Vincent and the Grenadines?', 'Kingstown'],
  ['What is the capital of Samoa?', 'Apia'],
  ['What is the capital of San Marino?', 'San Marino'],
  ['What is the capital of São Tomé and Príncipe?', 'São Tomé'],
  ['What is the capital of Saudi Arabia?', 'Riyadh'],
  ['What is the capital of Scotland?', 'Edinburgh'],
  ['What is the capital of Senegal?', 'Dakar'],
  ['What is the capital of Serbia?', 'Belgrade'],
  ['What is the capital of Seychelles?', 'Victoria'],
  ['What is the capital of Sierra Leone?', 'Freetown'],
  ['What is the capital of Singapore?', 'Singapore'],
  ['What is the capital of Sint Maarten?', 'Philipsburg'],
  ['What is the capital of Slovakia?', 'Bratislava'],
  ['What is the capital of Slovenia?', 'Ljubljana'],
  ['What is the capital of Solomon Islands?', 'Honiara'],
  ['What is the capital of Somalia?', 'Mogadishu'],
  ['What is the capital of Somaliland?', 'Hargeisa'],
  [
    'What is the capital of South Africa?',
    'Bloemfontein (judicial);  Cape Town (legislative);  Pretoria (executive)',
  ],
  [
    'What is the capital of South Georgia and the South Sandwich Islands?',
    'King Edward Point',
  ],
  [
    'What is the capital of South Korea?',
    'Seoul; Sejong City (de facto). On 2 July 2012, some functions of government moved to Sejong, which became the de facto administrative capital of South Korea.',
  ],
  ['What is the capital of South Ossetia?', 'Tskhinvali'],
  ['What is the capital of South Sudan?', 'Juba'],
  ['What is the capital of Spain?', 'Madrid'],
  ['What is the capital of Sri Lanka?', 'Colombo (executive, judicial)'],
  ['What is the capital of Sudan?', 'Khartoum'],
  ['What is the capital of Suriname?', 'Paramaribo'],
  ['What is the capital of Sweden?', 'Stockholm'],
  ['What is the capital of Switzerland?', 'Bern (de facto)'],
  ['What is the capital of Syria?', 'Damascus'],
  ['What is the capital of Taiwan?', 'Taipei'],
  ['What is the capital of Tajikistan?', 'Dushanbe'],
  [
    'What is the capital of Tanzania?',
    'Dodoma (official, legislative); Dar es Salaam (de facto, judicial)',
  ],
  ['What is the capital of Thailand?', 'Bangkok'],
  ['What is the capital of The Gambia?', 'Banjul'],
  ['What is the capital of Togo?', 'Lomé'],
  ['What is the capital of Tonga?', 'Nukuʻalofa'],
  ['What is the capital of Transnistria?', 'Tiraspol'],
  ['What is the capital of Trinidad and Tobago?', 'Port of Spain'],
  ['What is the capital of Tunisia?', 'Tunis'],
  ['What is the capital of Turkey?', 'Ankara'],
  ['What is the capital of Turkmenistan?', 'Ashgabat'],
  ['What is the capital of Turks and Caicos Islands?', 'Cockburn Town'],
  ['What is the capital of Tuvalu?', 'Funafuti'],
  ['What is the capital of Uganda?', 'Kampala'],
  ['What is the capital of Ukraine?', 'Kyiv'],
  ['What is the capital of United Arab Emirates?', 'Abu Dhabi'],
  ['What is the capital of United Kingdom?', 'London'],
  ['What is the capital of United States?', 'Washington, D.C.'],
  ['What is the capital of United States Virgin Islands?', 'Charlotte Amalie'],
  ['What is the capital of Uruguay?', 'Montevideo'],
  ['What is the capital of Uzbekistan?', 'Tashkent'],
  ['What is the capital of Vanuatu?', 'Port Vila'],
  ['What is the capital of Vatican City?', 'Vatican City'],
  ['What is the capital of Venezuela?', 'Caracas'],
  ['What is the capital of Vietnam?', 'Hanoi'],
  ['What is the capital of Wales?', 'Cardiff'],
  ['What is the capital of Wallis and Futuna?', 'Mata Utu'],
  [
    'What is the capital of Western Sahara?',
    'Laâyoune (declared);  Tifariti (de facto)',
  ],
  [
    'What is the capital of Yemen?',
    "Sana'a (de jure); Aden (de facto, temporary). Sana'a has been occupied by Houthi rebels since February 2015.",
  ],
  ['What is the capital of Zambia?', 'Lusaka'],
  ['What is the capital of Zimbabwe?', 'Harare'],
  ['For which country is this the capital? "Sukhumi"', 'Abkhazia'],
  ['For which country is this the capital? "Kabul"', 'Afghanistan'],
  ['For which country is this the capital? "Mariehamn"', 'Åland Islands'],
  ['For which country is this the capital? "Tirana"', 'Albania'],
  ['For which country is this the capital? "Algiers"', 'Algeria'],
  [
    'For which country is this the capital? "Sri Jayawardenepura Kotte (official)"',
    'Also known as Kotte.',
  ],
  ['For which country is this the capital? "Pago Pago"', 'American Samoa'],
  ['For which country is this the capital? "Andorra la Vella"', 'Andorra'],
  ['For which country is this the capital? "Luanda"', 'Angola'],
  ['For which country is this the capital? "The Valley"', 'Anguilla'],
  [
    'For which country is this the capital? "St. John\'s (de facto)"',
    'Antigua and Barbuda',
  ],
  ['For which country is this the capital? "Buenos Aires"', 'Argentina'],
  ['For which country is this the capital? "Yerevan"', 'Armenia'],
  ['For which country is this the capital? "Stepanakert"', 'Artsakh'],
  ['For which country is this the capital? "Oranjestad"', 'Aruba'],
  ['For which country is this the capital? "Georgetown"', 'Ascension Island'],
  ['For which country is this the capital? "Canberra"', 'Australia'],
  ['For which country is this the capital? "Vienna"', 'Austria'],
  ['For which country is this the capital? "Baku"', 'Azerbaijan'],
  ['For which country is this the capital? "Nassau"', 'Bahamas'],
  ['For which country is this the capital? "Manama"', 'Bahrain'],
  ['For which country is this the capital? "Dhaka"', 'Bangladesh'],
  ['For which country is this the capital? "Bridgetown"', 'Barbados'],
  ['For which country is this the capital? "Minsk"', 'Belarus'],
  ['For which country is this the capital? "Brussels"', 'Belgium'],
  ['For which country is this the capital? "Belmopan"', 'Belize'],
  [
    'For which country is this the capital? "Porto-Novo (official); Cotonou (de facto)"',
    'Benin',
  ],
  ['For which country is this the capital? "Hamilton"', 'Bermuda'],
  ['For which country is this the capital? "Thimphu"', 'Bhutan'],
  [
    'For which country is this the capital? "La Paz (administrative); Sucre (constitutional)"',
    'Bolivia',
  ],
  [
    'For which country is this the capital? "Sarajevo"',
    'Bosnia and Herzegovina',
  ],
  ['For which country is this the capital? "Gaborone"', 'Botswana'],
  [
    'For which country is this the capital? "Brasília. Rio de Janeiro was the capital until 1960."',
    'Brazil',
  ],
  [
    'For which country is this the capital? "Rothera"',
    'British Antarctic Territory',
  ],
  [
    'For which country is this the capital? "Camp Thunder Cove"',
    'British Indian Ocean Territory',
  ],
  [
    'For which country is this the capital? "Road Town"',
    'British Virgin Islands',
  ],
  ['For which country is this the capital? "Bandar Seri Begawan"', 'Brunei'],
  ['For which country is this the capital? "Sofia"', 'Bulgaria'],
  ['For which country is this the capital? "Ouagadougou"', 'Burkina Faso'],
  [
    'For which country is this the capital? "Gitega (official); Bujumbura (de facto). Bujumbura was the capital from 1962 to 2018."',
    'Burundi',
  ],
  ['For which country is this the capital? "Phnom Penh"', 'Cambodia'],
  ['For which country is this the capital? "Yaoundé"', 'Cameroon'],
  ['For which country is this the capital? "Ottawa"', 'Canada'],
  ['For which country is this the capital? "Praia"', 'Cape Verde'],
  ['For which country is this the capital? "George Town"', 'Cayman Islands'],
  [
    'For which country is this the capital? "Bangui"',
    'Central African Republic',
  ],
  ['For which country is this the capital? "N\'Djamena"', 'Chad'],
  [
    'For which country is this the capital? "Santiago (official); Valparaíso (legislative). The National Congress of Chile is located in Valparaíso."',
    'Chile',
  ],
  ['For which country is this the capital? "Beijing"', 'China'],
  [
    'For which country is this the capital? "Flying Fish Cove"',
    'Christmas Island',
  ],
  [
    'For which country is this the capital? "West Island"',
    'Cocos (Keeling) Islands',
  ],
  ['For which country is this the capital? "Bogotá"', 'Colombia'],
  ['For which country is this the capital? "Moroni"', 'Comoros'],
  ['For which country is this the capital? "Brazzaville"', 'Congo'],
  ['For which country is this the capital? "Avarua"', 'Cook Islands'],
  ['For which country is this the capital? "San José"', 'Costa Rica'],
  ['For which country is this the capital? "Zagreb"', 'Croatia'],
  ['For which country is this the capital? "Havana"', 'Cuba'],
  ['For which country is this the capital? "Willemstad"', 'Curaçao'],
  [
    'For which country is this the capital? "Nicosia"',
    'Cyprus / Northern Cyprus',
  ],
  [
    'For which country is this the capital? "Prague (official, legislative and executive); Brno (judiciary)"',
    'Czech Republic',
  ],
  [
    'For which country is this the capital? "Kinshasa"',
    'Democratic Republic of the Congo',
  ],
  ['For which country is this the capital? "Copenhagen"', 'Denmark'],
  ['For which country is this the capital? "Djibouti"', 'Djibouti'],
  ['For which country is this the capital? "Roseau"', 'Dominica'],
  [
    'For which country is this the capital? "Santo Domingo"',
    'Dominican Republic',
  ],
  ['For which country is this the capital? "Dili"', 'East Timor'],
  ['For which country is this the capital? "Quito"', 'Ecuador'],
  ['For which country is this the capital? "Cairo"', 'Egypt'],
  ['For which country is this the capital? "San Salvador"', 'El Salvador'],
  ['For which country is this the capital? "Malabo"', 'Equatorial Guinea'],
  ['For which country is this the capital? "Asmara"', 'Eritrea'],
  ['For which country is this the capital? "Tallinn"', 'Estonia'],
  [
    'For which country is this the capital? "Lobamba (royal and legislative); Mbabane (administrative)"',
    'Eswatini',
  ],
  ['For which country is this the capital? "Addis Ababa"', 'Ethiopia'],
  ['For which country is this the capital? "Stanley"', 'Falkland Islands'],
  ['For which country is this the capital? "Tórshavn"', 'Faroe Islands'],
  ['For which country is this the capital? "Suva"', 'Fiji'],
  ['For which country is this the capital? "Helsinki"', 'Finland'],
  ['For which country is this the capital? "Paris"', 'France'],
  ['For which country is this the capital? "Papeete"', 'French Polynesia'],
  ['For which country is this the capital? "Libreville"', 'Gabon'],
  ['For which country is this the capital? "Tbilisi"', 'Georgia'],
  ['For which country is this the capital? "Berlin"', 'Germany'],
  ['For which country is this the capital? "Accra"', 'Ghana'],
  ['For which country is this the capital? "Gibraltar"', 'Gibraltar'],
  ['For which country is this the capital? "Athens"', 'Greece'],
  ['For which country is this the capital? "Nuuk"', 'Greenland'],
  ['For which country is this the capital? "St. George\'s"', 'Grenada'],
  ['For which country is this the capital? "Hagåtña"', 'Guam'],
  ['For which country is this the capital? "Guatemala City"', 'Guatemala'],
  ['For which country is this the capital? "St. Peter Port"', 'Guernsey'],
  ['For which country is this the capital? "Conakry"', 'Guinea'],
  ['For which country is this the capital? "Bissau"', 'Guinea-Bissau'],
  ['For which country is this the capital? "Georgetown"', 'Guyana'],
  ['For which country is this the capital? "Port-au-Prince"', 'Haiti'],
  [
    'For which country is this the capital? "Tegucigalpa / Comayagüela. Comayagüela is declared in the Honduran Constitution as co-official capital with Tegucigalpa.[11] Now they have merged into a single Metropolitan Area."',
    'Honduras',
  ],
  ['For which country is this the capital? "Budapest"', 'Hungary'],
  ['For which country is this the capital? "Reykjavík"', 'Iceland'],
  ['For which country is this the capital? "New Delhi"', 'India'],
  ['For which country is this the capital? "Jakarta"', 'Indonesia'],
  ['For which country is this the capital? "Tehran"', 'Iran'],
  ['For which country is this the capital? "Baghdad"', 'Iraq'],
  ['For which country is this the capital? "Dublin"', 'Ireland'],
  ['For which country is this the capital? "Douglas"', 'Isle of Man'],
  [
    'For which country is this the capital? "Jerusalem; Palestine; Ramallah (de facto)"',
    'Israel',
  ],
  ['For which country is this the capital? "Rome"', 'Italy'],
  ['For which country is this the capital? "Yamoussoukro"', 'Ivory Coast'],
  ['For which country is this the capital? "Kingston"', 'Jamaica'],
  ['For which country is this the capital? "Tokyo"', 'Japan'],
  ['For which country is this the capital? "St. Helier"', 'Jersey'],
  ['For which country is this the capital? "Amman"', 'Jordan'],
  ['For which country is this the capital? "Astana"', 'Kazakhstan'],
  ['For which country is this the capital? "Nairobi"', 'Kenya'],
  ['For which country is this the capital? "South Tarawa"', 'Kiribati'],
  ['For which country is this the capital? "Pristina"', 'Kosovo'],
  ['For which country is this the capital? "Kuwait City"', 'Kuwait'],
  ['For which country is this the capital? "Bishkek"', 'Kyrgyzstan'],
  ['For which country is this the capital? "Vientiane"', 'Laos'],
  ['For which country is this the capital? "Riga"', 'Latvia'],
  ['For which country is this the capital? "Beirut"', 'Lebanon'],
  ['For which country is this the capital? "Maseru"', 'Lesotho'],
  ['For which country is this the capital? "Monrovia"', 'Liberia'],
  ['For which country is this the capital? "Tripoli"', 'Libya'],
  ['For which country is this the capital? "Vaduz"', 'Liechtenstein'],
  ['For which country is this the capital? "Vilnius"', 'Lithuania'],
  ['For which country is this the capital? "Luxembourg"', 'Luxembourg'],
  ['For which country is this the capital? "Antananarivo"', 'Madagascar'],
  ['For which country is this the capital? "Lilongwe"', 'Malawi'],
  [
    'For which country is this the capital? "Kuala Lumpur (official, legislative and royal); Putrajaya (administrative and judicial)"',
    'Malaysia',
  ],
  ['For which country is this the capital? "Malé"', 'Maldives'],
  ['For which country is this the capital? "Bamako"', 'Mali'],
  ['For which country is this the capital? "Valletta"', 'Malta'],
  ['For which country is this the capital? "Majuro"', 'Marshall Islands'],
  ['For which country is this the capital? "Nouakchott"', 'Mauritania'],
  ['For which country is this the capital? "Port Louis"', 'Mauritius'],
  ['For which country is this the capital? "Mexico City"', 'Mexico'],
  ['For which country is this the capital? "Palikir"', 'Micronesia'],
  ['For which country is this the capital? "Chișinău"', 'Moldova'],
  ['For which country is this the capital? "Monaco"', 'Monaco'],
  ['For which country is this the capital? "Ulaanbaatar"', 'Mongolia'],
  [
    'For which country is this the capital? "Podgorica (official); Cetinje (Old Royal Capital, present seat of the President)"',
    'Montenegro',
  ],
  [
    'For which country is this the capital? "Brades (de facto); Plymouth (official)"',
    'Montserrat',
  ],
  ['For which country is this the capital? "Rabat"', 'Morocco'],
  ['For which country is this the capital? "Maputo"', 'Mozambique'],
  ['For which country is this the capital? "Naypyidaw"', 'Myanmar'],
  ['For which country is this the capital? "Windhoek"', 'Namibia'],
  ['For which country is this the capital? "Yaren (de facto)"', 'Nauru'],
  ['For which country is this the capital? "Kathmandu"', 'Nepal'],
  [
    'For which country is this the capital? "Amsterdam (official); The Hague (de facto). The Dutch constitution refers to Amsterdam as the "capital""',
    'Netherlands',
  ],
  ['For which country is this the capital? "Nouméa"', 'New Caledonia'],
  ['For which country is this the capital? "Wellington"', 'New Zealand'],
  ['For which country is this the capital? "Managua"', 'Nicaragua'],
  ['For which country is this the capital? "Niamey"', 'Niger'],
  ['For which country is this the capital? "Abuja"', 'Nigeria'],
  ['For which country is this the capital? "Alofi"', 'Niue'],
  ['For which country is this the capital? "Kingston"', 'Norfolk Island'],
  ['For which country is this the capital? "Pyongyang"', 'North Korea'],
  ['For which country is this the capital? "Skopje"', 'North Macedonia'],
  ['For which country is this the capital? "Belfast"', 'Northern Ireland'],
  [
    'For which country is this the capital? "Saipan"',
    'Northern Mariana Islands',
  ],
  ['For which country is this the capital? "Oslo"', 'Norway'],
  ['For which country is this the capital? "Muscat"', 'Oman'],
  ['For which country is this the capital? "Islamabad"', 'Pakistan'],
  ['For which country is this the capital? "Ngerulmud"', 'Palau'],
  ['For which country is this the capital? "Panama City"', 'Panama'],
  ['For which country is this the capital? "Port Moresby"', 'Papua New Guinea'],
  ['For which country is this the capital? "Asunción"', 'Paraguay'],
  ['For which country is this the capital? "Lima"', 'Peru'],
  ['For which country is this the capital? "Manila"', 'Philippines'],
  ['For which country is this the capital? "Adamstown"', 'Pitcairn Islands'],
  ['For which country is this the capital? "Warsaw"', 'Poland'],
  ['For which country is this the capital? "Lisbon"', 'Portugal'],
  ['For which country is this the capital? "San Juan"', 'Puerto Rico'],
  ['For which country is this the capital? "Doha"', 'Qatar'],
  ['For which country is this the capital? "Bucharest"', 'Romania'],
  ['For which country is this the capital? "Moscow"', 'Russia'],
  ['For which country is this the capital? "Kigali"', 'Rwanda'],
  ['For which country is this the capital? "Gustavia"', 'Saint Barthélemy'],
  ['For which country is this the capital? "Jamestown"', 'Saint Helena'],
  [
    'For which country is this the capital? "Basseterre"',
    'Saint Kitts and Nevis',
  ],
  ['For which country is this the capital? "Castries"', 'Saint Lucia'],
  ['For which country is this the capital? "Marigot"', 'Saint Martin'],
  [
    'For which country is this the capital? "St. Pierre"',
    'Saint Pierre and Miquelon',
  ],
  [
    'For which country is this the capital? "Kingstown"',
    'Saint Vincent and the Grenadines',
  ],
  ['For which country is this the capital? "Apia"', 'Samoa'],
  ['For which country is this the capital? "San Marino"', 'San Marino'],
  [
    'For which country is this the capital? "São Tomé"',
    'São Tomé and Príncipe',
  ],
  ['For which country is this the capital? "Riyadh"', 'Saudi Arabia'],
  ['For which country is this the capital? "Edinburgh"', 'Scotland'],
  ['For which country is this the capital? "Dakar"', 'Senegal'],
  ['For which country is this the capital? "Belgrade"', 'Serbia'],
  ['For which country is this the capital? "Victoria"', 'Seychelles'],
  ['For which country is this the capital? "Freetown"', 'Sierra Leone'],
  ['For which country is this the capital? "Singapore"', 'Singapore'],
  ['For which country is this the capital? "Philipsburg"', 'Sint Maarten'],
  ['For which country is this the capital? "Bratislava"', 'Slovakia'],
  ['For which country is this the capital? "Ljubljana"', 'Slovenia'],
  ['For which country is this the capital? "Honiara"', 'Solomon Islands'],
  ['For which country is this the capital? "Mogadishu"', 'Somalia'],
  ['For which country is this the capital? "Hargeisa"', 'Somaliland'],
  [
    'For which country is this the capital? "Bloemfontein (judicial); Cape Town (legislative); Pretoria (executive)"',
    'South Africa',
  ],
  [
    'For which country is this the capital? "King Edward Point"',
    'South Georgia and the South Sandwich Islands',
  ],
  [
    'For which country is this the capital? "Seoul; Sejong City (de facto). On 2 July 2012, some functions of government moved to Sejong, which became the de facto administrative capital of South Korea."',
    'South Korea',
  ],
  ['For which country is this the capital? "Tskhinvali"', 'South Ossetia'],
  ['For which country is this the capital? "Juba"', 'South Sudan'],
  ['For which country is this the capital? "Madrid"', 'Spain'],
  [
    'For which country is this the capital? "Colombo (executive, judicial)"',
    'Sri Lanka',
  ],
  ['For which country is this the capital? "Khartoum"', 'Sudan'],
  ['For which country is this the capital? "Paramaribo"', 'Suriname'],
  ['For which country is this the capital? "Stockholm"', 'Sweden'],
  ['For which country is this the capital? "Bern (de facto)"', 'Switzerland'],
  ['For which country is this the capital? "Damascus"', 'Syria'],
  ['For which country is this the capital? "Taipei"', 'Taiwan'],
  ['For which country is this the capital? "Dushanbe"', 'Tajikistan'],
  [
    'For which country is this the capital? "Dodoma (official, legislative); Dar es Salaam (de facto, judicial)"',
    'Tanzania',
  ],
  ['For which country is this the capital? "Bangkok"', 'Thailand'],
  ['For which country is this the capital? "Banjul"', 'The Gambia'],
  ['For which country is this the capital? "Lomé"', 'Togo'],
  ['For which country is this the capital? "Nukuʻalofa"', 'Tonga'],
  ['For which country is this the capital? "Tiraspol"', 'Transnistria'],
  [
    'For which country is this the capital? "Port of Spain"',
    'Trinidad and Tobago',
  ],
  ['For which country is this the capital? "Tunis"', 'Tunisia'],
  ['For which country is this the capital? "Ankara"', 'Turkey'],
  ['For which country is this the capital? "Ashgabat"', 'Turkmenistan'],
  [
    'For which country is this the capital? "Cockburn Town"',
    'Turks and Caicos Islands',
  ],
  ['For which country is this the capital? "Funafuti"', 'Tuvalu'],
  ['For which country is this the capital? "Kampala"', 'Uganda'],
  ['For which country is this the capital? "Kyiv"', 'Ukraine'],
  [
    'For which country is this the capital? "Abu Dhabi"',
    'United Arab Emirates',
  ],
  ['For which country is this the capital? "London"', 'United Kingdom'],
  [
    'For which country is this the capital? "Washington, D.C."',
    'United States',
  ],
  [
    'For which country is this the capital? "Charlotte Amalie"',
    'United States Virgin Islands',
  ],
  ['For which country is this the capital? "Montevideo"', 'Uruguay'],
  ['For which country is this the capital? "Tashkent"', 'Uzbekistan'],
  ['For which country is this the capital? "Port Vila"', 'Vanuatu'],
  ['For which country is this the capital? "Vatican City"', 'Vatican City'],
  ['For which country is this the capital? "Caracas"', 'Venezuela'],
  ['For which country is this the capital? "Hanoi"', 'Vietnam'],
  ['For which country is this the capital? "Cardiff"', 'Wales'],
  ['For which country is this the capital? "Mata Utu"', 'Wallis and Futuna'],
  [
    'For which country is this the capital? "Laâyoune (declared); Tifariti (de facto)"',
    'Western Sahara',
  ],
  [
    'For which country is this the capital? "Sana\'a (de jure); Aden (de facto, temporary). Sana\'a has been occupied by Houthi rebels since February 2015."',
    'Yemen',
  ],
  ['For which country is this the capital? "Lusaka"', 'Zambia'],
  ['For which country is this the capital? "Harare"', 'Zimbabwe'],
];
